### ISSUE TITLE
Presumably non-exploitable vulnerabilities

### ISSUE THREAD

**Issue by collapsinghierharchy** [SasanLabs/VulnerableApp#270]
**Describe the bug**
1. Union/Blind/Error-SQLInjections >= LEVEL_3 are not exploitable. At least i was not able to find a Homoglyph that passes the "ReplaceAll"-Filter and cancels the single quote inside the query.
2. ArbitraryFileUpload/JWT-Tokens: Null-Byte-Attacks seem not to work. At least i was not able to find a null-byte sequence, that i can pass within a GET Request, that may work. (I did not yet try the XSSWithNullbytes)

**To Reproduce**
You may start Burp for example and try different GET queries. 

**Expected behavior**
The exploitation should work. 

**Additional context**
Obviously, these issue may arise from my incompetence and as such are no bugs at all. Therefore, i contacted the author of the application and he faced the same problems regarding the SQL-injections. Other Null-Bytes are additional observations afterwards and may be exploitable by means i did not come up with. (In this case i would like someone to shed light on how they are epected to be exploited.)
I'm using the official docker container.

**Would you like to help fix this issue?**
I'm ready to help. In fact, i suggest to present the exploitation solutions within the documentation.

**Comment by preetkaran20** [comment]
While working on this task there are few things very important we need to look:
1. Enhancing AttackVector annotation/Configuration to be more explicit to tell the exact payloads for exploitations and also create a way to register a new payload (calling a new api and add that payload) if someone encounters a new payload for the exploit.
2. SQL injection can be made vulnerable by relying on URL instead of queryparam so that %26 etc hexencoded values cannot be replaced but still can be executable in SQL.
3. Clearly marking vulnerabilities non exploitable so that users are not confused on whether it is not exploitable or they are not able to exploit it as mentioned above by @collapsinghierharchy 
4. Need to verify the jwt thing but as per my understanding it is possible to exploit it. 

@collapsinghierharchy, i think JWTVulnerability is vulnerable to Null Byte attack, code reference: https://github.com/SasanLabs/VulnerableApp/blob/01bce442b917080aba045a6d1b7b3c3cc628453f/src/main/java/org/sasanlabs/service/vulnerability/jwt/impl/JWTValidator.java#L64

Also FileUpload should also be exploitable: https://github.com/SasanLabs/VulnerableApp/blob/01bce442b917080aba045a6d1b7b3c3cc628453f/src/main/java/org/sasanlabs/service/vulnerability/fileupload/UnrestrictedFileUpload.java#L268
I think payload for fileupload should be `.html\0.jpeg` -> `\0` represent null byte, you need to use burp to insert a character with hex value as `00`

thanks,
Karan

**Comment by collapsinghierharchy** [comment]
Thx for the advice for using burp to insert a null byte instead of encoding it myself in case of the file upload. I've got this working now. Also with jwt i was able to trigger the vulnerability with manually adding %00 to the signature s.t. the rest of the signature is ignored. 
Therefore the issues under (2) are resolved. 

What i'm still wondering about is whe usefulness of the jwt nullbyte attack? Apart from the invalidation of the signature i dont see any value in this attack. What am i missing? 

Thank you

**Comment by preetkaran20** [comment]
Yeah, jwt with null byte is not very exploitable vulnerability. I am thinking how can null byte be used for creating a vulnerable code. Any thoughts?

**Comment by preetkaran20** [comment]
For SQL Injection:
please look at https://github.com/SasanLabs/VulnerableApp/blob/master/src/main/java/org/sasanlabs/service/vulnerability/pathTraversal/PathTraversalVulnerability.java#L146 for better understand on how to make the SQLInjection Vulnerabilities exploitable.

Files for SQLInjection are:
https://github.com/SasanLabs/VulnerableApp/tree/master/src/main/java/org/sasanlabs/service/vulnerability/sqlInjection

**Comment by preetkaran20** [comment]
@MadhuMadhavanSridhar

**Comment by preetkaran20** [comment]
I was checking FileUpload Vulnerability and i think the Vulnerability level_9 is not exploitable.

**Comment by marcin-wrotecki** [comment]
As discussed with @preetkaran20, @nowakkamil and I are going to work on this issue.

**Comment by marcin-wrotecki** [comment]
The issue is about checking which levels of Union/Blind/Error-SQLInjections and UnrestrictedFileUpload are secure and mark it. Second part is finding a payload which can exploit the mentioned vulnerabilities. Then, payload should be added to properties files. Change the name of curlPayload parameter in AttackVector adnotation to payload. In UI it should be changed too.
